-- MySQL Script generated by MySQL Workbench
-- Fri Dec 22 16:06:15 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `cod_usuario` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `cod_produto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`editora` (
  `cod_editora` INT NOT NULL,
  `telefone_1` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_editora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `cod_autor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_autor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `cod_categoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livro` (
  `cod_livro` INT NOT NULL,
  `nome` VARCHAR(25) NOT NULL,
  `categoriaID` VARCHAR(50) NOT NULL,
  `autorID` VARCHAR(45) NOT NULL,
  `anoDpublicação` INT NOT NULL,
  `cod_editora` INT NOT NULL,
  `autor_cod_autor` INT NOT NULL,
  `categoria_cod_categoria` INT NOT NULL,
  PRIMARY KEY (`cod_livro`),
  INDEX `cod_autor_idx` (`autor_cod_autor` ASC) VISIBLE,
  INDEX `cod_editora_idx` (`cod_editora` ASC) VISIBLE,
  INDEX `fk_livro_categoria1_idx` (`categoria_cod_categoria` ASC) VISIBLE,
  CONSTRAINT `cod_editora`
    FOREIGN KEY (`cod_editora`)
    REFERENCES `mydb`.`editora` (`cod_editora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_autor`
    FOREIGN KEY (`autor_cod_autor`)
    REFERENCES `mydb`.`autor` (`cod_autor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_categoria1`
    FOREIGN KEY (`categoria_cod_categoria`)
    REFERENCES `mydb`.`categoria` (`cod_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `cod_fornecedor` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `estoque_cod_livro` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_fornecedor`, `estoque_cod_livro`),
  INDEX `fk_fornecedor_estoque1_idx` (`estoque_cod_livro` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_estoque1`
    FOREIGN KEY (`estoque_cod_livro`)
    REFERENCES `mydb`.`estoque` (`cod_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `cod_livro` INT NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `cod_fornecedor` INT NULL,
  PRIMARY KEY (`cod_livro`),
  INDEX `cod_fornecedor_idx` (`cod_fornecedor` ASC) VISIBLE,
  CONSTRAINT `cod_livro`
    FOREIGN KEY ()
    REFERENCES `mydb`.`livro` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_fornecedor`
    FOREIGN KEY (`cod_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereço` (
  `idendereço` INT NOT NULL,
  PRIMARY KEY (`idendereço`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autoria` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`telefone` (
  `telefone` VARCHAR(15) NOT NULL,
  `Usuário_cod_usuario` VARCHAR(20) NULL,
  `cod_telefone` INT NOT NULL,
  `fornecedor_cod_fornecedor` INT NULL,
  PRIMARY KEY (`cod_telefone`),
  INDEX `fk_telefone_Usuário1_idx` (`Usuário_cod_usuario` ASC) VISIBLE,
  INDEX `fk_telefone_fornecedor1_idx` (`fornecedor_cod_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_telefone_Usuário1`
    FOREIGN KEY (`Usuário_cod_usuario`)
    REFERENCES `mydb`.`Usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefone_fornecedor1`
    FOREIGN KEY (`fornecedor_cod_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `cod_endereço` INT NOT NULL,
  `cep` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `bairrro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numerodacasa` VARCHAR(5) NOT NULL,
  `Usuário_cod_usuario` VARCHAR(20) NULL,
  `fornecedor_cod_fornecedor` INT NULL,
  PRIMARY KEY (`cod_endereço`),
  INDEX `fk_endereço_Usuário1_idx` (`Usuário_cod_usuario` ASC) VISIBLE,
  INDEX `fk_endereço_fornecedor1_idx` (`fornecedor_cod_fornecedor` ASC) VISIBLE,
  CONSTRAINT `fk_endereço_Usuário1`
    FOREIGN KEY (`Usuário_cod_usuario`)
    REFERENCES `mydb`.`Usuario` (`cod_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereço_fornecedor1`
    FOREIGN KEY (`fornecedor_cod_fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`cod_fornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho` (
  `cod_usuario` VARCHAR(45) NOT NULL,
  `idcarrinho` INT NOT NULL,
  PRIMARY KEY (`idcarrinho`),
  INDEX `cod_usuario_idx` (`cod_usuario` ASC) VISIBLE,
  CONSTRAINT `autorID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`livro` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cod_usuario`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `mydb`.`Usuario` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrinho_has_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrinho_has_pedido` (
  `qtd_pedido` INT NOT NULL,
  `total` VARCHAR(45) NOT NULL,
  `produto_cod_produto` INT NOT NULL,
  `carrinho_idcarrinho` INT NOT NULL,
  PRIMARY KEY (`produto_cod_produto`, `carrinho_idcarrinho`),
  INDEX `fk_carrinho_has_pedido_carrinho1_idx` (`carrinho_idcarrinho` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_has_pedido_produto1`
    FOREIGN KEY (`produto_cod_produto`)
    REFERENCES `mydb`.`produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carrinho_has_pedido_carrinho1`
    FOREIGN KEY (`carrinho_idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `cod_compra` INT NULL,
  `idcarrinho` INT NOT NULL,
  `dataCompra` DATE NOT NULL,
  PRIMARY KEY (`cod_compra`),
  INDEX `idcarrinho_idx` (`idcarrinho` ASC) VISIBLE,
  CONSTRAINT `idcarrinho`
    FOREIGN KEY (`idcarrinho`)
    REFERENCES `mydb`.`carrinho` (`idcarrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
